### ISSUE TITLE
Add additional filter

### ISSUE THREAD

**Issue by mattsobol77** [linuxserver/davos#10]
Adding a filter for what you DON'T want to download would add some flexibility.

**Comment by JAGFin1** [comment]
Are you happy for this functionality to be mutually exclusive to the existing logic? Having "exclusion" filters counters the current implementation, so if I implement this, it'll be exclusively include, or exclusively exclude.

**Comment by mattsobol77** [comment]
That would work fine I think, thanks for taking a look at it!

Do you have anything setup for a donation?

Thanks,

Cam

**Comment by JAGFin1** [comment]
No problem. I'll see what i can do in the next couple of days. Hopefully i can get a 2.1.0 release out by next weekend. 

Donations are very kind and always welcome! I don't have anything set up personally but the LSIO group has a page if you did want to donate. Developers are powered by beer after all! https://www.linuxserver.io/donations

Cheers.

**Comment by JAGFin1** [comment]
I've finished implementing this in the 2.1.0 branch. I've tested it locally and it seems to be behaving correctly. I'll get this merged into the master branch once I've finished clearing out the rest of the backlog.

Cheers.

**Comment by mattsobol77** [comment]
Great, looking forward to it!!

Cam
