### ISSUE TITLE
Allow custom shell scripts to run as a downstream option

### ISSUE THREAD

**Issue by mneumark** [linuxserver/davos#12]
It would be really useful to trigger a shell script to run with some environment variables (like $DOWNLOAD_DIR or $DOWNLOADED_FILE_PATH) set.

**Comment by JAGFin1** [comment]
This is something I had considered, however as a lot of the user base uses this inside docker, the shell script would only be in the scope of the container. Clever volume mapping would probably get around this problem. There's also the user that runs the application to consider too (what permissions the user has, etc).

Could you give an example of how you would use the environment variables in a command?

**Comment by mneumark** [comment]
Well, honestly the main thing is that I need to delete files from the server after they are downloaded. So if that feature were supported shell script support wouldn't be needed.

**Comment by JAGFin1** [comment]
Being able to delete the file on the server once the download has completed is actually not a bad idea. Are you happy for me to add that in as a feature instead of shell script execution?

**Comment by mneumark** [comment]
Yeah, that would be awesome!

**Comment by JAGFin1** [comment]
I've finished the implementation of this. Once I've gone through the other 2.1.0 features I'll get this released.

**Comment by mneumark** [comment]
Sweet! Thanks a lot!

**Comment by mneumark** [comment]
Those new features are awesome! I just disabled my crappy custom script and switched to davos in FreeNAS Corral. Works great!

**Comment by JAGFin1** [comment]
Glad to hear it! If you spot any bugs or have more feature requests, please do add to the issue list. I'll try my best to look at them.
