### ISSUE TITLE
Add "Run Now" button

### ISSUE THREAD

**Issue by mneumark** [linuxserver/davos#13]
It would be nice if each schedule had a "Run Now" button so in addition to the scheduled run, it could be run right then if need be.

**Comment by JAGFin1** [comment]
Is this separate in requirement to "Stop" and "Start"? 

For example, if you had an hourly run that runs on the hour, but you want a run to occur at 20 minutes past the hour, a stop/start would work. The con to this is that the schedule will now run every hour, 20 minutes past the hour.

**Comment by mneumark** [comment]
I guess I figured it would have no bearing on the schedule. Run it now and it'll still run in twenty minutes for an hourly schedule. It's just that you happen to know files are waiting and you want to get it to run then.

**Comment by JAGFin1** [comment]
I'll have a look into the APIs I'm using for this. I'm making use of the Java scheduling APIs which allows me to create an indefinite schedule which queues up if the previous run is still processing (actually a nice built-in feature). To get an ad-hoc run of a schedule I'll need to understand what kind of impact it would have if it doesn't finish before the next allotted schedule run (as each run updates its config so the next run can omit any files it's already scanned).

I'll let you know if I can do this.

**Comment by JAGFin1** [comment]
It is unlikely I'm going to implement this. If this is a show stopper, please re-open this issue.
