### ISSUE TITLE
Sub-folders scanning

### ISSUE THREAD

**Issue by PastaGringo** [linuxserver/davos#27]
Hello !

Firstly Davos is exactly the app that I'm looking for a long time 👍

I installed Davos with Docker, configured my host, and created a schedule to copy some folders that I need to download. My schedule settings (to begin) are very basics: download everything new with recursive mode (folders with their contents). So I don't modified anything except activating Recursive mode.

The FTP has this following directory structure :

```
/
 directory0/ <--------- Davos don't download files/folders above this one
            directoryA/ 
                       directory1/
                                 fileA
                       file1 
                       file2
            directoryB/ <--------- Davos downloads files/folders above this one
                       directory1/
                                 fileA
                       file1
                       file2  
```

When I setup the Host Directory with the Directory0 path, no files or folders are triggered.
When I setup the Host Directory with directoryA/B, folders and files are triggered and downloaded.

Do you know why ?

Thanks for your help !

**Comment by JAGFin1** [comment]
Hi!

Unfortunately as it stands, the recursive nature only applies to the download portion of the scan. The filtering occurs only on the directory you specify in the Host Directory field (it won't look in sub directories for matches). The idea was that if the scan matches a directory, davos will also download the contents of that directory. It's a way to tell davos to only download matches if they are files, or also if they are directories.

At least, I believe this is the behaviour you're experiencing. I assume your filters are on "directoryA" and "directoryB"?
