### ISSUE TITLE
Encryption after grabbing the data

### ISSUE THREAD

**Issue by ptTrR** [linuxserver/davos#35]
Hey Guys, 

mostly that image is perfectly. But if there is a possibility to integrate it into that images, that it is automatically encrypted after grabbing (as function) would be a nice extra into the container. 
A AES256 RAR Encryption, should be mostly enough. 

For example duplicatis solutions isnt my thing, cause there backup encryption, which only works over them. 

Regards. #34

**Comment by j0nnymoe** [comment]
Not something we're going to implement but you can customise the containers with the info here: https://blog.linuxserver.io/2019/09/14/customizing-our-containers/
