### ISSUE TITLE
No Filter = No Download

### ISSUE THREAD

**Issue by j0nnymoe** [linuxserver/davos#5]
Change the filter download behaviour to be "If no label present, don't download anything" instead of "No label, grab everything".

**Comment by JAGFin1** [comment]
I'll add a separate option (checkbox) in the Filters section that states:

"If this is checked, davos will not download any files unless a filter has been specified for it. If left unchecked, davos will download _all new_ files compared to the previous scan (or all files if first scan).

**Comment by JAGFin1** [comment]
Feature implemented. Part of 2.1.0.
